
# # Example config

# version: '3.2'

# services:
#   car-thing-builder:
#     image: bishopdynamics/car-thing-builder:latest
#     container_name: car_thing_builder
#     build: .
services:
  u-boot:
    platform: linux/amd64
    build: .
    # user: root
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./dist:/dist
# volumes:
#   workspace:
#     driver: local
#   build_output: 
#     driver: local
  
